server:
  port: 8080
  context-path: /
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/music?useUnicode=true&characterEncoding=utf-8
    username: music
    password: music@album100
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update